function ProtocolBatchFile = readProtocBatchCSV(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PROTOCOLBATCHTEMPLATE = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  PROTOCOLBATCHTEMPLATE = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  ProtocolBatchTemplate = importfile("C:\Users\Konrad\Documents\MATLAB\fNIRS\2022_StimCrtlGui\ProtocolBatchTemplate.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Nov-2023 15:53:47

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Time", "Type", "Channels", "Amplitude", "PulseWidth", "Duration", "Freq", "BurstPulseCount", "BurstFreq"];
opts.VariableTypes = ["char", "string", "char",     "double",     "double",    "double",   "double", "double",        "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
% opts = setvaropts(opts, ["Time", "Type", "Channels"], "WhitespaceRule", "preserve");
% opts = setvaropts(opts, ["Time", "Type", "Channels"], "EmptyFieldRule", "auto");
% opts = setvaropts(opts, ["BurstPulses", "BurstFreq"], "TrimNonNumeric", true);
% opts = setvaropts(opts, ["BurstPulses", "BurstFreq"], "ThousandsSeparator", ",");

% Import the data
ProtocolBatchFile = readtable(filename, opts);

end